### PR TITLE
Improve language settings dialog

### PR DESCRIPTION
**Pull request by remarcmij**

### CODE REVIEW

**Comment by profxed** [comment]
Looks great.
I may add to this an `i18next` addition I missed in the previous PR, is that okay for this branch?

**Review by profxed — APPROVED** [review]

**Comment by remarcmij** [comment]
> Looks great.
> I may add to this an `i18next` addition I missed in the previous PR, is that okay for this?branch?

Yes, please do.

**Comment by profxed** [comment]
done, Thank you. shall we merge?

**Comment by remarcmij** [comment]
> done, Thank you. shall we merge?

Thanks Jawhar, I just did.

**Pull request merged**
